#!/bin/bash

## Read freesurfer directory from json file
fsdir=`cat args.json | jq -r ".fs"`

## Initialize freesurfer
FREESURFER_HOME=$fsdir
source $FREESURFER_HOME/SetUpFreeSurfer.sh

## Read project folder path from json file
projpath=`cat args.json | jq -r ".out"`

## Read in subject textfile
txtfile=$1

## Read in timepoint to use
tval=`cat args.json | jq -r ".timeval"`

## Read in number of cores per fs instance
fscore=`cat args.json | jq -r '.numcore'`


## Set freesurfer subject dir
export SUBJECTS_DIR=$projpath"/"$tval"/fsproc"


for file in `cat $txtfile`; do
	if ! grep -Fxq $file $projpath"/"$tval"/fsproc/fs_run.txt"; then
		echo "Running recon-all on "$file

		t1=$projpath"/"$tval"/matproc/"$file"/acpc/t1_acpc.nii.gz"
		echo $t1
		recon-all -all -parallel -openmp $fscore -s $file -i $t1

	fi
done
