#!/bin/bash

## Establish path to project folder
projpath=`cat args.json | jq -r '.out'`

## Establish path to template MNI brain
template=`cat args.json | jq -r '.template'`

## Read in timepoint to use
tval=`cat args.json | jq -r '.timeval'`

## Generate matproc dir in project folder based on year
if ! test -d $projpath"/"$tval"/matproc"; then
	mkdir $projpath"/"$tval"/matproc"
fi

## Read in textfile containing subject IDs
txtfile=`cat args.json | jq -r '.txt'`

## Append .txt extension if it isn't already present
if [[ $txtfile != *".txt" ]]; then
	txtfile=$txtfile".txt"
fi


#loop through subject names
for name in `cat $txtfile`; do

	#create matproc subject directory
	echo $name
	if ! test -d $projpath"/"$tval"/matproc/"$name; then
		mkdir $projpath"/"$tval"/matproc/"$name
		mkdir $projpath"/"$tval"/matproc/"$name"/acpc"
	fi
	#create matproc subject acpc directory
	if ! test -d $projpath"/"$tval"/matproc/"$name"/acpc"; then
		mkdir $projpath"/"$tval"/matproc/"$name"/acpc"
	fi

	#create path to subject bids t1
	input=$projpath"/"$tval"/bids/"$name"/anat/sub-"$name*".nii"
	#create output path and output filename for acpc aligned file
	outdir=$projpath"/"$tval"/matproc/"$name"/acpc"
	output=$outdir"/"t1_acpc.nii.gz	


	echo "Performing auto-acpc alignment..."
	#begin acpc alignment
	robustfov -i $input -m $outdir'/'roi2full.mat -r $outdir'/'input_robustfov.nii.gz
        convert_xfm -omat $outdir'/'full2roi.mat -inverse $outdir'/'roi2full.mat
        flirt -interp spline -in $outdir'/'input_robustfov.nii.gz -ref $template -omat $outdir'/'roi2std.mat -out $outdir'/'acpc_mni.nii.gz
        convert_xfm -omat $outdir'/'full2std.mat -concat $outdir'/'roi2std.mat $outdir'/'full2roi.mat
        aff2rigid $outdir'/'full2std.mat $outdir'/'outputmatrix

	applywarp --rel --interp=spline -i $input -r $template --premat=$outdir"/"outputmatrix -o $output


done
