#!/bin/bash

echo "Inputs will be used to create json file"
echo "Leave blank processes you will not perform"
echo ""
echo "Input path to project directory (outputs will be stored here):"
read output
echo ""
echo "Input path to template brain for ACPC-alignment (neglect .nii extension)"
read template
echo ""
echo "Input path to subject text file:"
read txtfile
echo ""
while true; do
	echo "Input timepoint (Baseline, 2Year, 4Year):"
	read tval
	if [ "$tval" = "Baseline" ] || [ "$tval" = "2Year" ] || [ "$tval" = "4Year" ]; then
		break
	fi
	echo "Error: do not recognize timepoint. Please input Baseline, 2Year, or 4Year"
done

JSON_STRING=$( jq -n \
		--arg out $output \
		--arg txt $txtfile \
		--arg temp $template \
		--arg tp $tval \
		'{out: $out, txt: $txt, template: $temp, timeval: $tp}' )



echo $JSON_STRING >> args.json
