#!/bin/bash

#set path to matproc dir
matprocPath='/mnt/acorn/ethan/matproc'

#set path to brain templates
templatePath='/mnt/acorn/ethan/scripts/templates'

#set path to subject textfile (use anat)
txtfile='/mnt/acorn/ethan/scripts/anat/subs.txt'

matlab -nodisplay -nosplash -nodesktop -r "ants_affine_warp('$matprocPath', '$templatePath', '$txtfile');exit;"
