#!/bin/bash

## Establish path to raw tar files
tarpath=`cat args.json | jq -r '.dmri'`

## Establish path to project folder
projpath=`cat args.json | jq -r '.out'`

## Read in timepoint to use
tval=`cat args.json | jq -r '.timeval'`

## Generate bids dir in project folder based on year, if it does not already exist
if ! test -d $projpath"/"$tval; then
	mkdir $projpath"/"$tval
	mkdir $projpath"/"$tval"/bids"
fi
if ! test -d $projpath"/"$tval"/bids"; then
	mkdir $projpath"/"$tval"/bids"
fi


## Read in textfile containing subject IDs
txtfile=`cat args.json | jq -r '.txt'`

## Append .txt extension if it isn't already present
if [[ $txtfile != *".txt" ]]; then
	txtfile=$txtfile".txt"
fi


## Loop through subject names
for name in `cat $txtfile`; do

	echo $name
	if ! test -d $projpath"/"$tval"/bids/"$name; then
		mkdir $projpath"/"$tval"/bids/"$name
		mkdir $projpath"/"$tval"/bids/"$name"/dmri"
	fi

	if ! test -d $projpath"/"$tval"/bids/"$name"/dmri"; then
		mkdir $projpath"/"$tval"/bids/"$name"/dmri"
	fi

	tarfiles=`ls -f $tarpath | grep $name"_"$tval`

	for file in $tarfiles; do
		echo $file
		tar -xf $tarpath"/"$file -C $projpath"/"$tval"/bids/"$name"/dmri"
	done

	## Move files into desired directory and remove extraneous folders
	mv $projpath"/"$tval"/bids/"$name"/dmri/sub-"$name"/"*"/dwi/"* $projpath"/"$tval"/bids/"$name"/dmri/."
	rm $projpath"/"$tval"/bids/"$name"/dmri/sub-"$name -r
done

