#!/bin/bash

## Read in project folder from json file
projpath=`cat args.json | jq -r ".out"`


## set template brain paths
mni_temp=$projpath"/masks/MNI152_T1_1mm_brain.nii.gz"
tlrc_temp=$projpath"/masks/TT_N27+tlrc."


## Read in subject textfile
txtfile=$1

## Read in timepoint to use
tval=`cat args.json | jq -r ".timeval"`

for subject in `cat $txtfile`; do

		##create subject folder, if it does not already exist
		if ! test -d $projpath"/"$tval"/afniproc/"$subject; then
			mkdir $projpath"/"$tval"/afniproc/"$subject
		fi

		## Copy subject MID scans 1 and 2 from bids folder into afniproc,
		## rename to mid1.nii.gz and mid2.nii.gz
		cp $projpath"/"$tval"/bids/"$subject"/fmri/"*"run-01_bold.nii" $projpath"/"$tval"/afniproc/"$subject"/mid1.nii.gz"
		cp $projpath"/"$tval"/bids/"$subject"/fmri/"*"run-02_bold.nii" $projpath"/"$tval"/afniproc/"$subject"/mid2.nii.gz"


		## Copy subject T1 scan from bids folder into afniproc
		cp $projpath"/"$tval"/bids/"$subject"/anat/"*"T1w.nii" $projpath"/"$tval"/afniproc/"$subject"/t1.nii.gz"


		if test -f $projpath"/"$tval"/afniproc/"$subject"/mid1.nii.gz" && test -f $projpath"/"$tval"/afniproc/"$subject"/mid2.nii.gz"; then

			echo $subject
			cd $projpath"/"$tval"/afniproc/"$subject

			#convert anatomical scan to brick and header
			if test -f anat+orig.HEAD; then
		        	rm -rf anat+orig*
		        fi

		        3dcopy "t1.nii.gz" anat

			#convert files to ANFI, cut off leadin/leadout
			if test -f epi1+orig.HEAD; then
				rm -rf epi?+orig*
			fi

			#cut the first 8 TRs (so indices 8-410)
			3dTcat -prefix epi1 "mid1.nii.gz[8..410]"
			3dTcat -prefix epi2 "mid2.nii.gz[8..410]"

			#refitting + slice time correction
			3drefit -TR 0.8 epi1+orig.
			3drefit -TR 0.8 epi2+orig.

			if test -f epits1+orig.HEAD; then
				rm -rf epits?+orig*
			fi

			3dTshift -slice 0 -tpattern altplus -prefix epits1 epi1+orig.
			3dTshift -slice 0 -tpattern altplus -prefix epits2 epi2+orig.

			#rm -rf epi?+orig*

			#pre-clean

			if test -f mid+orig.HEAD; then
				rm -rf mid+orig*
			fi

			#create concatenated dataset
			3dTcat -prefix mid epits1+orig epits2+orig

			rm -rf epits?+orig*

			#correct for motion

			if test -f mid_m+orig.HEAD; then
				rm -rf mid_m+orig*
			fi

			if test -f 3dmotionmid.1D; then
				rm -rf 3dmotionmid.1D
			fi

			3dvolreg -Fourier -twopass -prefix mid_m -base 3 -dfile 3dmotionmid.1D mid+orig

			#smooth spatially
			if test -f mid_mb+orig.HEAD; then
				rm -rf mid_mb+orig*
			fi

			3dmerge -prefix mid_mb -1blur_fwhm 4 -doall mid_m+orig

			#normalize (calculate pct signal change / average) and filter

			if test -f mid_mbn+orig.BRIK; then
				rm -rf mid_mbn+orig*
			fi

			if test -f mid_ave+orig.BRIK; then
				rm -rf mid_ave+*
			fi

			#should end at 805
			3dTstat -prefix mid_ave "mid_mb+orig[0..805]"
			3drefit -abuc mid_ave+orig
			3dcalc -datum float -a "mid_mb+orig[0..805]" -b mid_ave+orig -expr "((a-b)/b)*100" -prefix mid_mbn


			#high pass filter
			if test -f mid_mbnf+orig.HEAD; then
				rm -rf mid_mbnf+orig.*
			fi


			3dTproject -prefix mid_mbnf -stopband 0 .011 -input mid_mbn+orig


			#talairach warping

			#preclean directory

			if test -f anat+tlrc.HEAD; then
				rm -rf anat+tlrc.*
			fi


			#xform to tlrc brain
			@auto_tlrc -warp_orig_vol -suffix NONE -base $tlrc_temp -input anat+orig.


			#xform to MNI brain
			@auto_tlrc -warp_orig_vol -suffix mni -base $mni_temp -input anat+orig.


			#set the epi parent to the auto-warped anat
			3drefit -apar anat+orig mid_mbnf+orig

		fi
done
