#!/bin/bash

#set path to location of tar files
tar_path='/mnt/bacon/raw/abcd/fmri/Package_1224211/fmriresults01/abcd-mproc-release5'

#set path to location to untar (should be a bids folder)
extract_path='/mnt/acorn/ethan/bids'

#set path to list of subject files to untar
#NOTE: for abcd siemens data, each subject has TWO tar files for a given session.
#	This corresponds to run 1 and run 2. Subject mid data can only be processed
#	if they have both of these runs!
sub_list='/mnt/acorn/ethan/scripts/fmri/subs.txt'



#move into the directory for file placement
cd $extract_path

#loop through subject files, untar from tar location to extract location
for file in `cat $sub_list`; do
	echo $file #print out working file to terminal
	tar_file=$tar_path'/'$file #construct path to subject tar file
	tar -xf $tar_file #untar subject file


	#abcd data is organized in bids format already
done
